### ISSUE TITLE
ArchytasTool 3.8识别不了设备

### ISSUE THREAD

**Issue by SkyTommyzhang** [rpOneawa/ArchytasTool#1]
最近群中许多新成员使用群文件中的ArchytasTool反映无法识别设备，用老版本就行

**Comment by SkyTommyzhang** [comment]
![8NBZ~3E_))))U~L0`8 Q~6N](https://user-images.githubusercontent.com/71883368/162741177-2e7ebb92-ef1a-47f4-a335-7abb0655247f.jpg)
Q群@Eternity提供

**Comment by rponeawa** [comment]
是连接之后再运行工具的吗
